# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data News
email: 'info[@]datanews.io'
description: Data news for data enthusiasts and scientists
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://datanews.io" # the base hostname & protocol for your site
twitter_username: datanewsio
facebook_username:  datanewsio

predefined_categories: ['dataset', 'nlp', 'deep learning', 'question', 'data mining']

# Build settings
markdown: kramdown
